# Generated by Django 4.2.4 on 2023-09-01 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='videos_requested', to=settings.AUTH_USER_MODEL),
        ),
    ]
