# Generated by Django 4.2.4 on 2023-09-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='dislikes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
