# Generated by Django 4.2.4 on 2023-09-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_manager', '0003_remove_video_author_video_ytuser_ytuser_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_link',
        ),
        migrations.RemoveField(
            model_name='ytuser',
            name='subscribers_count',
        ),
        migrations.RemoveField(
            model_name='ytuser',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ytuser',
            name='user_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
