# Generated by Django 4.2.4 on 2023-09-01 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos_manager', '0004_remove_video_video_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='video',
            name='likes',
        ),
    ]
