# Generated by Django 4.2.4 on 2023-09-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_manager', '0005_remove_video_dislikes_remove_video_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
